#!/usr/bin/env bash
# ==============================================================================
# MUTATION TESTING: TIER 2 (App Services + Actions)
# Runs post-PR to gate MSI degradation in critical business logic.
# ==============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_FILE="$ROOT_DIR/infection-extended.json5"
MIN_MSI="${INFECTION_MIN_MSI:-95}"
MIN_COVERED_MSI="${INFECTION_MIN_COVERED_MSI:-95}"
THREADS="${INFECTION_THREADS:-10}"
TIMEOUT_MINUTES="${INFECTION_TIMEOUT_MINUTES:-90}"
MEMORY_LIMIT="${INFECTION_MEMORY_LIMIT:-4G}"

echo "🧬 Mutation Testing: Tier 2 (app/Services + app/Actions)"
echo "========================================================"
echo "Configuration: $CONFIG_FILE"
echo "Thresholds: MSI ≥ $MIN_MSI, Covered MSI ≥ $MIN_COVERED_MSI (baseline: 100/100)"
echo "Threads: $THREADS"
echo "Timeout: ${TIMEOUT_MINUTES} minutes"
echo "Mutation memory limit: ${MEMORY_LIMIT}"
echo ""

# Verify coverage XML and JUnit report exist (both required when using --skip-initial-tests).
# These MUST be pre-generated by check-line-coverage.sh in the same pest run to guarantee
# consistency. If either is missing, fail immediately — do NOT re-collect here, since a
# separate collection step will produce artifacts from a different test run, causing
# class-name mismatches (TestFileNameNotFoundException).
COVERAGE_DIR="$ROOT_DIR/storage/infection/coverage"
JUNIT_FILE="$COVERAGE_DIR/junit.xml"
RUN_LOG="$ROOT_DIR/reports/infection-run.log"
TEXT_LOG="$ROOT_DIR/reports/infection-extended.log"
SUMMARY_JSON="$ROOT_DIR/reports/infection-extended-summary.json"

if [ ! -f "$COVERAGE_DIR/index.xml" ]; then
    echo "❌ Coverage XML missing: $COVERAGE_DIR/index.xml"
    echo "   Run check-line-coverage.sh first."
    exit 1
fi

if [ ! -f "$JUNIT_FILE" ]; then
    echo "❌ JUnit report missing: $JUNIT_FILE"
    echo "   Run check-line-coverage.sh first (it produces both coverage XML and JUnit)."
    exit 1
fi

echo "✅ Prerequisites found:"
echo "   Coverage: $COVERAGE_DIR/index.xml"
echo "   JUnit:    $JUNIT_FILE"
echo ""

echo "🛠️  Normalizing JUnit metadata for Infection"
php "$ROOT_DIR/scripts/testing/normalize-pest-junit-for-infection.php" "$JUNIT_FILE"

# Run Infection using pre-collected coverage XML (avoids 25-min redundant test re-run)
# --coverage: path to Xdebug coverage XML dir (collected by check-line-coverage.sh)
# --skip-initial-tests: don't re-run the full suite; use the coverage we already have
# --only-covering-test-cases: only run tests that cover the specific mutant (huge speedup)
# PHP_INI_SCAN_DIR: use a temporary copy of conf.d WITHOUT xdebug to avoid extension
#   loading overhead on every mutant subprocess (~5-10% speedup per mutant).
NOXDEBUG_SCAN_DIR=$(mktemp -d)
for ini in /usr/local/etc/php/conf.d/*.ini; do
    case "$(basename "$ini")" in
        *xdebug*) ;; # skip xdebug
        *) cp "$ini" "$NOXDEBUG_SCAN_DIR/" ;;
    esac
done

timeout $((TIMEOUT_MINUTES * 60)) \
    env XDEBUG_MODE=off PHP_INI_SCAN_DIR="$NOXDEBUG_SCAN_DIR" \
    php -d xdebug.mode=off -d memory_limit="${MEMORY_LIMIT}" "$ROOT_DIR/vendor/bin/infection" \
    --configuration="$CONFIG_FILE" \
    --coverage="$ROOT_DIR/storage/infection/coverage" \
    --skip-initial-tests \
    --only-covering-test-cases \
    --threads="$THREADS" \
    --no-progress \
    --min-msi="$MIN_MSI" \
    --min-covered-msi="$MIN_COVERED_MSI" \
    --logger-text="$TEXT_LOG" \
    --logger-summary-json="$SUMMARY_JSON" \
    2>&1 | tee "$RUN_LOG"

EXIT_CODE=${PIPESTATUS[0]}

rm -rf "$NOXDEBUG_SCAN_DIR"

# Parse results
if [ -f "$SUMMARY_JSON" ]; then
    echo ""
    echo "📊 Mutation Summary (Tier 2):"
    php -r "
        \$data = json_decode(file_get_contents('$SUMMARY_JSON'), true);
        \$stats = \$data['stats'] ?? [];
        printf(\"  MSI: %d / 100\n\", \$stats['msi'] ?? 0);
        printf(\"  Covered MSI: %d / 100\n\", \$stats['coveredCodeMsi'] ?? 0);
        printf(\"  Killed: %d / %d\n\", \$stats['killedCount'] ?? 0, \$stats['totalMutantsCount'] ?? 0);
        printf(\"  Escaped: %d\n\", \$stats['escapedCount'] ?? 0);
        printf(\"  Errors: %d\n\", \$stats['errorCount'] ?? 0);
    " || true
fi

if [ $EXIT_CODE -eq 0 ]; then
    echo ""
    echo "✅ Tier 2 mutation testing PASSED."
    exit 0
else
    echo ""
    echo "❌ Tier 2 mutation testing FAILED."
    if [ "$EXIT_CODE" -eq 137 ]; then
        echo "   Infection was killed by the OS (likely OOM)."
        echo "   Retry with fewer workers, e.g. INFECTION_THREADS=4."
    fi
    echo "   Review escaped mutants in: $TEXT_LOG"
    echo "   Full run log: $RUN_LOG"
    exit 1
fi
