<?php

declare(strict_types=1);

/**
 * Phase 1 baseline generator.
 *
 * Generates reports/testing-baseline-YYYY-MM-DD.md with:
 * - Unit base-class distribution
 * - Feature write-endpoint files lacking side-effect assertions
 * - Layer file distribution
 * - Median/p95 runtime from local test run logs
 * - CI lane runtime parsing when reports/ci_master.log is available
 */

final class TestingPhase1Baseline
{
    private string $root;

    public function __construct(string $root)
    {
        $this->root = rtrim($root, DIRECTORY_SEPARATOR);
    }

    public function run(): string
    {
        $date = date('Y-m-d');
        $outputFile = $this->root."/reports/testing-baseline-{$date}.md";

        $unitStats = $this->collectUnitBaseClassStats();
        $featureStats = $this->collectFeatureWriteAssertionDepthStats();
        $layerStats = $this->collectLayerDistributionStats();
        $runtimeStats = $this->collectLocalRuntimeStats();
        $ciLaneStats = $this->collectCiLaneRuntimeStats();

        $markdown = [];
        $markdown[] = '# Testing Baseline Report';
        $markdown[] = '';
        $markdown[] = 'Generated: '.date('c');
        $markdown[] = 'Phase: 1 (Baseline and Guardrails)';
        $markdown[] = '';

        $markdown[] = '## Unit Base-Class Distribution';
        $markdown[] = '';
        $markdown[] = '| Metric | Count |';
        $markdown[] = '|---|---:|';
        $markdown[] = '| Unit files scanned | '.$unitStats['files_scanned'].' |';
        $markdown[] = '| Extends PureUnitTestCase | '.$unitStats['pure_unit_count'].' |';
        $markdown[] = '| Extends UnitTestCase | '.$unitStats['framework_unit_count'].' |';
        $markdown[] = '| Other / unknown base | '.$unitStats['other_count'].' |';
        $markdown[] = '';

        $markdown[] = '## Feature Write-Endpoint Assertion Depth';
        $markdown[] = '';
        $markdown[] = '| Metric | Count |';
        $markdown[] = '|---|---:|';
        $markdown[] = '| Feature files scanned | '.$featureStats['files_scanned'].' |';
        $markdown[] = '| Files containing write requests | '.$featureStats['write_files_count'].' |';
        $markdown[] = '| Write files without side-effect assertions | '.$featureStats['shallow_write_files_count'].' |';
        $markdown[] = '';

        if ($featureStats['shallow_write_files_count'] > 0) {
            $markdown[] = '### Current Baseline Allowlist Candidates';
            $markdown[] = '';
            foreach ($featureStats['shallow_write_files'] as $path) {
                $markdown[] = '- '.$path;
            }
            $markdown[] = '';
        }

        $markdown[] = '## Layer File Distribution';
        $markdown[] = '';
        $markdown[] = '| Layer | File Count |';
        $markdown[] = '|---|---:|';
        foreach ($layerStats as $layer => $count) {
            $markdown[] = '| '.$layer.' | '.$count.' |';
        }
        $markdown[] = '';

        $markdown[] = '## Runtime Baseline';
        $markdown[] = '';
        $markdown[] = '### Local test-results log durations';
        $markdown[] = '';
        $markdown[] = '| Metric | Value |';
        $markdown[] = '|---|---:|';
        $markdown[] = '| Parsed log runs | '.$runtimeStats['count'].' |';
        $markdown[] = '| Median duration (seconds) | '.$runtimeStats['median_seconds'].' |';
        $markdown[] = '| p95 duration (seconds) | '.$runtimeStats['p95_seconds'].' |';
        $markdown[] = '';

        $markdown[] = '### CI lane runtime (latest CI log)';
        $markdown[] = '';
        if ($ciLaneStats['available'] === false) {
            $markdown[] = '- Unavailable: '.$ciLaneStats['reason'];
        } else {
            $markdown[] = '| Lane | Samples | Median (s) | p95 (s) |';
            $markdown[] = '|---|---:|---:|---:|';
            /** @var array<string, array{count:int, median:float, p95:float}> $lanes */
            $lanes = $ciLaneStats['lanes'];
            foreach ($lanes as $lane => $row) {
                $markdown[] = '| '.$lane.' | '.$row['count'].' | '.number_format($row['median'], 2).' | '.number_format($row['p95'], 2).' |';
            }
        }
        $markdown[] = '';

        $markdown[] = '## Notes';
        $markdown[] = '';
        $markdown[] = '- This report is generated by scripts/testing_phase1_baseline.php.';
        $markdown[] = '- Threshold baselines in guard tests should be derived from this file and then tightened over time.';
        $markdown[] = '';

        file_put_contents($outputFile, implode(PHP_EOL, $markdown).PHP_EOL);

        return $outputFile;
    }

    /**
     * @return array{files_scanned:int, pure_unit_count:int, framework_unit_count:int, other_count:int}
     */
    private function collectUnitBaseClassStats(): array
    {
        $files = $this->phpFilesIn($this->root.'/tests/Unit');

        $pure = 0;
        $framework = 0;
        $other = 0;

        foreach ($files as $file) {
            $contents = (string) file_get_contents($file);

            if (preg_match('/extends\s+PureUnitTestCase\b/', $contents) === 1) {
                $pure++;
                continue;
            }

            if (preg_match('/extends\s+UnitTestCase\b|extends\s+TestCase\b|uses\s*\(\s*Tests\\\\UnitTestCase::class\s*\)/', $contents) === 1) {
                $framework++;
                continue;
            }

            $other++;
        }

        return [
            'files_scanned' => count($files),
            'pure_unit_count' => $pure,
            'framework_unit_count' => $framework,
            'other_count' => $other,
        ];
    }

    /**
     * @return array{files_scanned:int, write_files_count:int, shallow_write_files_count:int, shallow_write_files:list<string>}
     */
    private function collectFeatureWriteAssertionDepthStats(): array
    {
        $files = $this->phpFilesIn($this->root.'/tests/Feature');
        $writeFiles = [];
        $shallowFiles = [];

        foreach ($files as $file) {
            $contents = (string) file_get_contents($file);
            if (! $this->containsWriteRequest($contents)) {
                continue;
            }

            $relativePath = $this->relativePath($file);
            $writeFiles[] = $relativePath;

            if (! $this->containsSideEffectAssertion($contents)) {
                $shallowFiles[] = $relativePath;
            }
        }

        sort($shallowFiles);

        return [
            'files_scanned' => count($files),
            'write_files_count' => count($writeFiles),
            'shallow_write_files_count' => count($shallowFiles),
            'shallow_write_files' => $shallowFiles,
        ];
    }

    /**
     * @return array{Unit:int, Feature:int, Integration:int, Browser:int}
     */
    private function collectLayerDistributionStats(): array
    {
        return [
            'Unit' => count($this->phpFilesIn($this->root.'/tests/Unit')),
            'Feature' => count($this->phpFilesIn($this->root.'/tests/Feature')),
            'Integration' => count($this->phpFilesIn($this->root.'/tests/Integration')),
            'Browser' => count($this->phpFilesIn($this->root.'/tests/Browser')),
        ];
    }

    /**
     * @return array{count:int, median_seconds:string, p95_seconds:string}
     */
    private function collectLocalRuntimeStats(): array
    {
        $logFiles = glob($this->root.'/reports/test-results-*.log') ?: [];
        $durations = [];

        foreach ($logFiles as $file) {
            // Skip .ansi.log files to avoid duplicate entries.
            if (str_ends_with($file, '.ansi.log')) {
                continue;
            }

            $contents = (string) file_get_contents($file);
            if (! preg_match('/Script started on (.+?) \[/', $contents, $startMatch)) {
                continue;
            }
            if (! preg_match('/Script done on (.+?) \[/', $contents, $endMatch)) {
                continue;
            }

            $start = strtotime($startMatch[1]);
            $end = strtotime($endMatch[1]);
            if ($start === false || $end === false || $end < $start) {
                continue;
            }

            $durations[] = (float) ($end - $start);
        }

        if ($durations === []) {
            return [
                'count' => 0,
                'median_seconds' => '0.00',
                'p95_seconds' => '0.00',
            ];
        }

        return [
            'count' => count($durations),
            'median_seconds' => number_format($this->quantile($durations, 0.50), 2),
            'p95_seconds' => number_format($this->quantile($durations, 0.95), 2),
        ];
    }

    /**
     * @return array{available:bool, reason?:string, lanes?:array<string, array{count:int, median:float, p95:float}>}
     */
    private function collectCiLaneRuntimeStats(): array
    {
        $ciLogPath = $this->root.'/reports/ci_master.log';
        if (! file_exists($ciLogPath)) {
            return [
                'available' => false,
                'reason' => 'reports/ci_master.log not found in workspace.',
            ];
        }

        $contents = (string) file_get_contents($ciLogPath);
        $laneDurations = [
            'guards' => [],
            'unit' => [],
            'feature' => [],
            'architecture' => [],
            'integration' => [],
        ];

        // Expected pattern examples handled:
        // - "unit-tests ... 42.33s"
        // - "feature ... duration=75.2"
        if (preg_match_all('/\b(guards?|unit(?:-tests)?|feature(?:-tests)?|architecture(?:-tests)?|integration(?:-tests)?)\b[^\n]*?(?:duration\s*[=:]\s*|\s)(\d+(?:\.\d+)?)\s*s?\b/i', $contents, $matches, PREG_SET_ORDER)) {
            foreach ($matches as $match) {
                $laneRaw = strtolower($match[1]);
                $seconds = (float) $match[2];

                $lane = match (true) {
                    str_contains($laneRaw, 'guard') => 'guards',
                    str_contains($laneRaw, 'unit') => 'unit',
                    str_contains($laneRaw, 'feature') => 'feature',
                    str_contains($laneRaw, 'architecture') => 'architecture',
                    str_contains($laneRaw, 'integration') => 'integration',
                    default => null,
                };

                if ($lane !== null) {
                    $laneDurations[$lane][] = $seconds;
                }
            }
        }

        $rows = [];
        foreach ($laneDurations as $lane => $durations) {
            if ($durations === []) {
                continue;
            }

            $rows[$lane] = [
                'count' => count($durations),
                'median' => $this->quantile($durations, 0.50),
                'p95' => $this->quantile($durations, 0.95),
            ];
        }

        if ($rows === []) {
            return [
                'available' => false,
                'reason' => 'reports/ci_master.log found but no parsable lane runtime lines were detected.',
            ];
        }

        return [
            'available' => true,
            'lanes' => $rows,
        ];
    }

    private function containsWriteRequest(string $contents): bool
    {
        return preg_match('/->\s*(post|postJson|put|putJson|patch|patchJson|delete|deleteJson)\s*\(/i', $contents) === 1;
    }

    private function containsSideEffectAssertion(string $contents): bool
    {
        return preg_match(
            '/assertDatabase(?:Has|Missing|Count)|assertDispatched|assertPushed|assertQueued|assertSent|assertNotified|assertExists\(|assertMissing\(|->refresh\(|->fresh\(|Cache::has\(|Cache::get\(/i',
            $contents
        ) === 1;
    }

    /**
     * @return list<string>
     */
    private function phpFilesIn(string $dir): array
    {
        if (! is_dir($dir)) {
            return [];
        }

        $files = [];
        $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
        foreach ($it as $file) {
            if (! $file->isFile() || $file->getExtension() !== 'php') {
                continue;
            }
            $files[] = $file->getPathname();
        }

        sort($files);

        return $files;
    }

    private function relativePath(string $absolutePath): string
    {
        return str_replace($this->root.DIRECTORY_SEPARATOR, '', $absolutePath);
    }

    /**
     * @param  list<float>  $values
     */
    private function quantile(array $values, float $q): float
    {
        sort($values);
        $n = count($values);
        if ($n === 0) {
            return 0.0;
        }
        if ($n === 1) {
            return $values[0];
        }

        $pos = ($n - 1) * $q;
        $lower = (int) floor($pos);
        $upper = (int) ceil($pos);
        if ($lower === $upper) {
            return $values[$lower];
        }

        $weight = $pos - $lower;

        return ($values[$lower] * (1.0 - $weight)) + ($values[$upper] * $weight);
    }
}

$generator = new TestingPhase1Baseline(dirname(__DIR__));
$path = $generator->run();

echo "Generated {$path}".PHP_EOL;
